export class SheetsRowResponse {
  'Company Name': string;
  'Stock Symbol': string;
  'Dividends V.S. Growth Portfolio': string;
  'RZ Buy/Hold/Sell Sentiment': string;
  'Peer Options': string;
  'Distribution Range': string;
  'Live Portfolio': string;
  '2021_05.27 10Y>170YT%+>4%Yld+>Top 50': string;
  '2021_05.27 10Y>170YT%+>4%Yld+>Top 40': string;
  Both: string;
  '2nd. Round Investment Choice': string;
  'Watch List': string;
  Rating: string;
  '10-Yr. Perf. Ranking': string;
  Category: string;
  'NAV CEF CONNECT PERF.': string;
  'Current Discount/Premium': string;
  '52wk. Ave. Discount/Premium': string;
  'Contrarian Outlook': string;
  'IG Port': string;
  'Tactical Port': string;
  'Tax. Port.': string;
  'Forbes Performance': string;
  'Forbes Cost': string;
  'Morning Star Rating': string;
  'Top Choice': string;
  'Seeking Alpha Chatter': string;
  'Payout Ratio': string;
  'Dividend Growth': string;
  '10 YR Momentum': string;
  'Fund V.S. Stock Portfolio': string;
  '2021_05.27 10Y>170YT%+>4%Yld+>Top 50>Rank By 10Yr Perf': string;
  'Stock Symbol (Continued)': string;
  'Current Premium/Discount': string;
  '52 Wk Avg. Premium/Discont': string;
  '52 Wk High Premium/Discount': string;
  '52 Wk Low Premium/Discount': string;
  'Distriubtion Frequency': string;
  'Share Price': string;
  'Estimated Income': string;
  Yield: string;
  '#Shares/$1 Invested': string;
  'Annual Income Per $1Invested': string;
  'Annual Income Per $100 Invested': string;
  'Money Invested': string;
  'Total Income': string;
  'Source Rec': string;
  'Code Field': string;
}
