name: Production Deploy
'on':
  push:
    branches:
      - main
      - master
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn --frozen-lockfile
  lint:
    runs-on: ubuntu-latest
    needs: ['install_dependencies']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: ['install_dependencies', 'lint']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - run: echo tests will go here
      # - run: yarn --frozen-lockfile
      # - run: yarn test:ci
  build:
    runs-on: ubuntu-latest
    needs: ['install_dependencies', 'lint', 'test']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn build

